Repository Zeronfinity/CPfy, pull requests merged in 2021-01, with the labels that each got.

#45 Add platform ID as key
  app/build.gradle
  app/src/main/java/com/zeronfinity/cpfy/model/PlatformMap.kt
  app/src/main/java/com/zeronfinity/cpfy/model/ServerContestInfoClist.kt
  app/src/main/java/com/zeronfinity/cpfy/model/ServerPlatformInfoClist.kt
  app/src/main/java/com/zeronfinity/cpfy/model/network/pojo/ClistContestObjectResponse.kt
  app/src/main/java/com/zeronfinity/cpfy/model/network/pojo/ClistResourceObjectResponse.kt
  app/src/main/java/com/zeronfinity/cpfy/view/adapter/AdapterContestList.kt
  app/src/main/java/com/zeronfinity/cpfy/view/adapter/AdapterPlatformFilters.kt
  app/src/main/java/com/zeronfinity/cpfy/viewmodel/ClipboardViewModel.kt
  app/src/main/java/com/zeronfinity/cpfy/viewmodel/FiltersViewModel.kt
  app/src/test/java/com/zeronfinity/cpfy/model/ContestArrayListTest.kt
  app/src/test/java/com/zeronfinity/cpfy/model/PlatformMapTest.kt
  app/src/test/java/com/zeronfinity/cpfy/model/ServerContestInfoClistTest.kt
  app/src/test/java/com/zeronfinity/cpfy/model/network/ClistNetworkCallTest.kt
  core/src/main/java/com/zeronfinity/core/entity/Contest.kt
  core/src/main/java/com/zeronfinity/core/entity/Platform.kt
  core/src/main/java/com/zeronfinity/core/repository/PlatformDataSource.kt
  core/src/main/java/com/zeronfinity/core/repository/PlatformRepository.kt
  core/src/main/java/com/zeronfinity/core/usecase/DisablePlatformUseCase.kt
  core/src/main/java/com/zeronfinity/core/usecase/EnablePlatformUseCase.kt
  core/src/main/java/com/zeronfinity/core/usecase/GetFilteredContestListUseCase.kt
  core/src/main/java/com/zeronfinity/core/usecase/GetPlatformUseCase.kt
  core/src/main/java/com/zeronfinity/core/usecase/IsPlatformEnabledUseCase.kt
Labels: enhancement

#46 Refactor framework directories
  app/build.gradle
  app/src/main/java/com/zeronfinity/cpfy/framework/di/ApplicationModule.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/di/NetworkModule.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/implementations/ContestArrayList.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/implementations/CookieSharedPreferences.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/implementations/FilterTimeRangeSharedPreferences.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/implementations/PlatformMap.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/implementations/ServerContestInfoClist.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/implementations/ServerPlatformInfoClist.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/network/ClistNetworkCall.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/network/pojo/ClistContestObjectResponse.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/network/pojo/ClistResourceObjectResponse.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/network/pojo/ClistServerResponseContests.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/network/pojo/ClistServerResponsePlatforms.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/network/retrofit/RetrofitClistApiClient.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/network/retrofit/RetrofitClistApiInterface.kt
  app/src/main/java/com/zeronfinity/cpfy/view/adapter/AdapterContestList.kt
  app/src/main/java/com/zeronfinity/cpfy/viewmodel/ContestListViewModel.kt
  app/src/test/java/com/zeronfinity/cpfy/implementations/ContestArrayListTest.kt
  app/src/test/java/com/zeronfinity/cpfy/implementations/CookieSharedPreferencesTest.kt
  app/src/test/java/com/zeronfinity/cpfy/implementations/FilterTimeRangeSharedPreferencesTest.kt
  app/src/test/java/com/zeronfinity/cpfy/implementations/PlatformMapTest.kt
  app/src/test/java/com/zeronfinity/cpfy/implementations/ServerContestInfoClistTest.kt
  app/src/test/java/com/zeronfinity/cpfy/implementations/network/ClistNetworkCallTest.kt
  app/src/test/java/com/zeronfinity/cpfy/network/ClistApiClientMock.kt
  build.gradle
Labels: enhancement

#48 Add database persistency for platform functionalities
  app/build.gradle
  app/schemas/com.zeronfinity.cpfy.framework.db.AppDatabase/1.json
  app/src/main/java/com/zeronfinity/cpfy/common/Constants.kt
  app/src/main/java/com/zeronfinity/cpfy/common/UtilityFunctions.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/db/AppDatabase.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/db/dao/BaseDao.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/db/dao/PlatformDao.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/db/entity/ContestEntity.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/db/entity/PlatformEntity.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/di/ActivityModule.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/di/ApplicationModule.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/di/DatabaseModule.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/implementations/PlatformDb.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/implementations/PlatformMap.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/implementations/ServerContestInfoClist.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/implementations/ServerPlatformInfoClist.kt
  app/src/main/java/com/zeronfinity/cpfy/view/ContestListFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/FiltersFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/adapter/AdapterContestList.kt
  app/src/main/java/com/zeronfinity/cpfy/view/adapter/AdapterPlatformFilters.kt
  app/src/main/java/com/zeronfinity/cpfy/viewmodel/ClipboardViewModel.kt
  app/src/main/java/com/zeronfinity/cpfy/viewmodel/ContestListViewModel.kt
  app/src/main/java/com/zeronfinity/cpfy/viewmodel/FiltersViewModel.kt
  app/src/main/res/drawable/ic_baseline_expand_less_24.xml
  app/src/main/res/drawable/ic_baseline_expand_more_24.xml
  app/src/main/res/layout/fragment_clipboard.xml
  app/src/main/res/layout/fragment_filters.xml
  app/src/main/res/values/colors.xml
  app/src/test/java/com/zeronfinity/cpfy/framework/implementations/ContestArrayListTest.kt
  app/src/test/java/com/zeronfinity/cpfy/framework/implementations/CookieSharedPreferencesTest.kt
  app/src/test/java/com/zeronfinity/cpfy/framework/implementations/FilterTimeRangeSharedPreferencesTest.kt
  app/src/test/java/com/zeronfinity/cpfy/framework/implementations/PlatformDbTest.kt
  app/src/test/java/com/zeronfinity/cpfy/framework/implementations/ServerContestInfoClistTest.kt
  app/src/test/java/com/zeronfinity/cpfy/framework/implementations/network/ClistNetworkCallTest.kt
  app/src/test/java/com/zeronfinity/cpfy/implementations/PlatformMapTest.kt
  core/src/main/java/com/zeronfinity/core/entity/Platform.kt
  core/src/main/java/com/zeronfinity/core/repository/PlatformDataSource.kt
  core/src/main/java/com/zeronfinity/core/repository/PlatformRepository.kt
  core/src/main/java/com/zeronfinity/core/usecase/DisableAllPlatformsUseCase.kt
  core/src/main/java/com/zeronfinity/core/usecase/EnableAllPlatformsUseCase.kt
  core/src/main/java/com/zeronfinity/core/usecase/GetFilteredContestListUseCase.kt
  core/src/main/java/com/zeronfinity/core/usecase/GetOrderedPlatformListUseCase.kt
  core/src/main/java/com/zeronfinity/core/usecase/GetPlatformListUseCase.kt
  core/src/main/java/com/zeronfinity/core/usecase/GetPlatformUseCase.kt
  core/src/main/java/com/zeronfinity/core/usecase/IsPlatformEnabledUseCase.kt
Labels: enhancement

#49 Fix platform fetch
  app/build.gradle
  app/src/main/java/com/zeronfinity/cpfy/CustomApplication.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/di/ActivityModule.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/implementations/ServerPlatformInfoClist.kt
  app/src/main/java/com/zeronfinity/cpfy/view/ContestListFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/WebViewFragment.kt
  core/src/main/java/com/zeronfinity/core/usecase/FetchServerContestInfoUseCase.kt
  core/src/main/java/com/zeronfinity/core/usecase/FetchServerPlatformInfoUseCase.kt
Labels: enhancement

#50 Update build-and-upload-debug.yml
  .github/workflows/build-and-upload-debug.yml
Labels: enhancement

#51 Use flow to get platform list
  app/src/main/java/com/zeronfinity/cpfy/framework/db/dao/PlatformDao.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/di/ActivityModule.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/implementations/PlatformDb.kt
  app/src/main/java/com/zeronfinity/cpfy/viewmodel/ContestListViewModel.kt
  app/src/test/java/com/zeronfinity/cpfy/framework/implementations/PlatformDbTest.kt
  core/build.gradle
  core/src/main/java/com/zeronfinity/core/repository/PlatformDataSource.kt
  core/src/main/java/com/zeronfinity/core/repository/PlatformRepository.kt
  core/src/main/java/com/zeronfinity/core/usecase/GetOrderedPlatformListUseCase.kt
  core/src/main/java/com/zeronfinity/core/usecase/GetPlatformListUseCase.kt
Labels: enhancement

#53 Add filter functionality to use lower bound as start of current date
  app/build.gradle
  app/src/main/java/com/zeronfinity/cpfy/framework/di/ActivityModule.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/implementations/FilterTimeRangeSharedPreferences.kt
  app/src/main/java/com/zeronfinity/cpfy/view/ContestListFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/DayPickerDiaFrag.kt
  app/src/main/java/com/zeronfinity/cpfy/view/FiltersFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/viewmodel/FiltersViewModel.kt
  app/src/main/res/layout/fragment_day_picker.xml
  app/src/main/res/layout/fragment_filters.xml
  app/src/main/res/navigation/nav_graph_main.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/zeronfinity/cpfy/framework/implementations/FilterTimeRangeSharedPreferencesTest.kt
  core/src/main/java/com/zeronfinity/core/repository/FilterTimeRangeDataSource.kt
  core/src/main/java/com/zeronfinity/core/repository/FilterTimeRangeRepository.kt
  core/src/main/java/com/zeronfinity/core/usecase/GetFilterDaysAfterTodayUseCase.kt
  core/src/main/java/com/zeronfinity/core/usecase/GetFilteredContestListUseCase.kt
  core/src/main/java/com/zeronfinity/core/usecase/IsFilterLowerBoundTodayUseCase.kt
  core/src/main/java/com/zeronfinity/core/usecase/SetFilterDaysAfterTodayUseCase.kt
  core/src/main/java/com/zeronfinity/core/usecase/SetFilterLowerBoundTodayUseCase.kt
Labels: enhancement

#59 Fix negative contest start time due to contest ending
  app/src/main/java/com/zeronfinity/cpfy/view/adapter/AdapterContestList.kt
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#61 Add swipe/pull down functionality to reload contest list page
  app/build.gradle
  app/src/main/java/com/zeronfinity/cpfy/broadcast/NotificationBroadcast.kt
  app/src/main/java/com/zeronfinity/cpfy/common/UtilityFunctions.kt
  app/src/main/java/com/zeronfinity/cpfy/view/ContestListFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/adapter/AdapterContestList.kt
  app/src/main/res/layout/fragment_contest_list.xml
Labels: enhancement

#62 Fix filter time sync issues
  app/src/main/java/com/zeronfinity/cpfy/view/ContestListFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/FiltersFragment.kt
  core/src/main/java/com/zeronfinity/core/usecase/FetchAndPersistServerContestsUseCase.kt
  core/src/main/java/com/zeronfinity/core/usecase/GetFilteredContestListFlowUseCase.kt
Labels: bug, enhancement

#63 Update bug_report.md and version
  .github/ISSUE_TEMPLATE/bug_report.md
  app/build.gradle
Labels: enhancement

#64 Add functionality to change priority of all notifications at once
  app/build.gradle
  app/src/main/java/com/zeronfinity/cpfy/broadcast/NotificationBroadcast.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/db/dao/PlatformDao.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/di/ActivityModule.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/di/NetworkModule.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/implementations/ContestDb.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/implementations/PlatformDb.kt
  app/src/main/java/com/zeronfinity/cpfy/view/NotificationFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/WebViewFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/adapter/AdapterPlatformFilters.kt
  app/src/main/java/com/zeronfinity/cpfy/viewmodel/NotificationViewModel.kt
  app/src/main/res/layout-v26/fragment_notification.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/item_notification_priority.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/zeronfinity/cpfy/framework/implementations/CookieSharedPreferencesTest.kt
  app/src/test/java/com/zeronfinity/cpfy/framework/implementations/FilterTimeRangeSharedPreferencesTest.kt
  app/src/test/java/com/zeronfinity/cpfy/framework/implementations/PlatformDbTest.kt
  core/src/main/java/com/zeronfinity/core/repository/PlatformDataSource.kt
  core/src/main/java/com/zeronfinity/core/repository/PlatformRepository.kt
  core/src/main/java/com/zeronfinity/core/usecase/SetAllNotificationPriorityUseCase.kt
Labels: enhancement

#65 Add about section
  app/build.gradle
  app/src/main/java/com/zeronfinity/cpfy/view/AboutFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/LicenseFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/adapter/AdapterLicenseList.kt
  app/src/main/res/layout/fragment_about.xml
  app/src/main/res/layout/fragment_license.xml
  app/src/main/res/layout/item_license.xml
  app/src/main/res/navigation/nav_graph_main.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle
  core/src/main/java/com/zeronfinity/core/entity/License.kt
Labels: enhancement

#66 Refactor code base to reduce flow hits from database
  app/build.gradle
  app/src/main/java/com/zeronfinity/cpfy/framework/implementations/ContestDb.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/implementations/PlatformDb.kt
  app/src/main/java/com/zeronfinity/cpfy/view/ContestListFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/FiltersFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/adapter/AdapterContestList.kt
  app/src/main/java/com/zeronfinity/cpfy/view/adapter/AdapterPlatformFilters.kt
  app/src/main/java/com/zeronfinity/cpfy/viewmodel/ContestListViewModel.kt
Labels: enhancement

#69 Fix notification issues and UI
  app/src/main/java/com/zeronfinity/cpfy/view/ContestListFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/NotificationFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/adapter/AdapterNotificationPriorities.kt
  app/src/main/res/layout-v26/fragment_notification.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#70 Fix license link in readme and update version
  app/build.gradle
  docs/README.md
Labels: enhancement

#71 Split enabled and disabled platforms into two lists in filter screen
  app/build.gradle
  app/src/main/java/com/zeronfinity/cpfy/common/Constants.kt
  app/src/main/java/com/zeronfinity/cpfy/common/Either.kt
  app/src/main/java/com/zeronfinity/cpfy/view/FiltersFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/adapter/AdapterDisabledPlatformFilters.kt
  app/src/main/java/com/zeronfinity/cpfy/view/adapter/AdapterEnabledPlatformFilters.kt
  app/src/main/res/layout/fragment_filters.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#72 Add functionality to select contests for clipboard
  app/build.gradle
  app/src/main/java/com/zeronfinity/cpfy/view/ClipboardFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/ContestListFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/WebViewFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/adapter/AdapterContestList.kt
  app/src/main/java/com/zeronfinity/cpfy/viewmodel/ClipboardViewModel.kt
  app/src/main/res/layout/fragment_clipboard.xml
  app/src/main/res/layout/item_contest.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#73 Fix small issues and add signing keys
  .github/workflows/test-and-upload-debug.yml
  .gitignore
  app/build.gradle
  app/src/main/java/com/zeronfinity/cpfy/framework/logger/AndroidLoggingHandler.kt
  app/src/main/java/com/zeronfinity/cpfy/view/ContestListFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/viewmodel/ContestListViewModel.kt
  app/src/main/res/layout/fragment_contest_list.xml
  debug-keystore.jks
  keystore.properties
Labels: enhancement

#75 Add first run welcome dialog
  app/build.gradle
  app/src/main/java/com/zeronfinity/cpfy/framework/di/ActivityModule.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/di/ApplicationModule.kt
  app/src/main/java/com/zeronfinity/cpfy/framework/implementations/FirstRunSharedPreferences.kt
  app/src/main/java/com/zeronfinity/cpfy/view/AboutFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/ClipboardFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/ContestListFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/DayPickerDiaFrag.kt
  app/src/main/java/com/zeronfinity/cpfy/view/DurationPickerDiaFrag.kt
  app/src/main/java/com/zeronfinity/cpfy/view/FiltersFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/FirstRunDiaFrag.kt
  app/src/main/java/com/zeronfinity/cpfy/view/LicenseFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/NotificationFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/WebViewFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/base/BaseDialogFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/view/base/BaseFragment.kt
  app/src/main/java/com/zeronfinity/cpfy/viewmodel/ContestListViewModel.kt
  app/src/main/res/layout-v26/fragment_first_run.xml
  app/src/main/res/layout/fragment_first_run.xml
  app/src/main/res/navigation/nav_graph_main.xml
  app/src/main/res/values/strings.xml
  core/src/main/java/com/zeronfinity/core/repository/FirstRunDataSource.kt
  core/src/main/java/com/zeronfinity/core/repository/FirstRunRepository.kt
  core/src/main/java/com/zeronfinity/core/usecase/IsFirstRunUseCase.kt
  core/src/main/java/com/zeronfinity/core/usecase/SetFirstRunUseCase.kt
Labels: enhancement

#78 Add device model to bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: enhancement

#79 Make About screen scrollable
  app/build.gradle
  app/src/main/res/layout/fragment_about.xml
Labels: enhancement

#82 Fix sync of filter recyclerview item count
  app/src/main/java/com/zeronfinity/cpfy/view/adapter/AdapterDisabledPlatformFilters.kt
  app/src/main/java/com/zeronfinity/cpfy/view/adapter/AdapterEnabledPlatformFilters.kt
  app/src/main/res/layout/fragment_filters.xml
Labels: bug, enhancement

#84 Add empty contest list texts
  app/build.gradle
  app/src/main/java/com/zeronfinity/cpfy/view/ContestListFragment.kt
  app/src/main/res/layout/fragment_contest_list.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#86 Fix first run welcome window not fully visible
  app/build.gradle
  app/src/main/res/layout-v26/fragment_first_run.xml
  app/src/main/res/layout/fragment_first_run.xml
  app/src/main/res/values/dimens.xml
Labels: bug

#85 Fix text cut off issue in notification menu
  app/src/main/res/layout-v26/fragment_notification.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement
